config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'sudoku#index'

  post 'sudoku/index'
  get 'sudoku/index'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sudoku.rb
class Sudoku
  def initialize(board)
    @board = board
  end

  def solve
    solve_board(0, 0)
  end

  private

  def solve_board(row, col)
    return true if row == 9

    if @board[row][col] != 0
      if col == 8
        solve_board(row + 1, 0)
      else
        solve_board(row, col + 1)
      end
    else
      (1..9).each do |num|
        if valid_move?(row, col, num)
          @board[row][col] = num

          if col == 8
            return true if solve_board(row + 1, 0)
          else
            return true if solve_board(row, col + 1)
          end
        end
      end

      @board[row][col] = 0
      return false
    end
  end

  def valid_move?(row, col, num)
    return false if @board[row].include?(num)

    return false if @board.transpose[col].include?(num)

    box_row = (row / 3) * 3
    box_col = (col / 3) * 3

    (box_row...box_row + 3).each do |r|
      (box_col...box_col + 3).each do |c|
        return false if @board[r][c] == num
      end
    end

    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sudoku_controller.rb
class SudokuController < ApplicationController
  def index
    @solution = Array.new(9) { Array.new(9, 0) }
    if request.post?
      @sudoku = parse_sudoku_params(params[:sudoku])

      if params.key?('solve')
        @solved_sudoku = SudokuSolver.solve(@sudoku)

        if @solved_sudoku
          @solution = @solved_sudoku
        else
          @solution = @sudoku
          @cant_solve = true
        end

      else
        @solution = @sudoku
        @is_solved = SudokuValidator.solved?(@sudoku)
      end

    end
  end

  private

  def parse_sudoku_params(sudoku_params)
    sudoku_params.to_unsafe_h.values.map { |row| row.values.map(&:to_i) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sudoku</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sudoku/index.html.erb
<div class="container">
  <h1>Введіть судоку</h1>
  <%= form_with url: sudoku_index_path, method: :post, local: true, data: { turbo: false } do |form| %>
    <table>
      <% 9.times do |row| %>
        <tr>
          <% 9.times do |col| %>
            <td>
              <%= form.number_field "sudoku[#{row}][#{col}]", min: 0, max: 9, class: "sudoku-input", value: @solution[row][col] %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
    <div class="button-panel">
      <%= button_tag "Рандом", type: "button", id: "randomize" %>
      <%= form.submit "Вирішити", name: "solve", class: "form-button" %>
      <%= form.submit "Перевірити", name: "check", class: "form-button" %>
    </div>
  <% end %>

  <% if @is_solved.present? %>

    <% if @is_solved == true %>
      <p>Судоку вирішено вірно!</p>
    <% end %>
  <% end %>

  <% if @cant_solve.present? %>
    <p>Немає рішень!</p>
  <% end %>
</div>


<style>

    .container {
        text-align: center;
        margin: auto;
        padding: 20px;
        background-color: #f2f2f2;
    }

    h1 {
        font-size: 24px;
        margin-bottom: 20px;
        color: #444444;
    }

    table {
        margin-bottom: 20px;
        border-collapse: collapse;
    }

    td {
        padding: 5px;
    }

    .sudoku-input {
        width: 30px;
        height: 30px;
        text-align: center;
        font-size: 16px;
        border: 1px solid #cccccc;
        background-color: #f9f9f9;
        color: #444444;
    }

    .button-panel {
        margin-bottom: 20px;
    }

    .form-button {
        margin-right: 10px;
        background-color: #666666;
        color: #ffffff;
        border: none;
        padding: 8px 16px;
        font-size: 14px;
        text-transform: uppercase;
        cursor: pointer;
    }

    p {
        margin-bottom: 10px;
        font-size: 18px;
        color: #444444;
    }

</style>